version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=5173
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
volumes:
  frontend_node_modules:
